-- Add frozenAt / frozenReason to Group
ALTER TABLE "Group" ADD COLUMN IF NOT EXISTS "frozenAt" TIMESTAMP;
ALTER TABLE "Group" ADD COLUMN "frozenReason" TEXT;

-- Add dispute resolution fields
ALTER TABLE "Dispute" ADD COLUMN "adminNotes" TEXT;
ALTER TABLE "Dispute" ADD COLUMN "resolvedBy" TEXT;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "resolvedAt" TIMESTAMP;

-- Expand NotificationType enum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYOUT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GROUP_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GROUP_STARTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GROUP_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GROUP_FROZEN';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GROUP_UNFROZEN';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GROUP_INVITE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'JOIN_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INVITE_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LATE_FEE_CHARGED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CYCLE_COMPLETE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WALLET_NOT_PROVISIONED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DEBIT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'KYC_REQUIRED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DISPUTE_OPENED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DISPUTE_RESOLVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DISPUTE_REJECTED';
